### ISSUE TITLE
Can't download remote model

### ISSUE THREAD

**Issue by salhugues** [googlecodelabs/automl-vision-edge-in-mlkit#1]
Hello, 

I have an issue, my application can't download the remote model. I have and 404 error which saying that it failed to connect to Firebase ML Console server.

Here is the details :

`com.google.firebase.ml.common.FirebaseMLException: Failed to schedule the download task
        at com.google.android.gms.internal.firebase_ml.zzoz.zzmi(Unknown Source:171)
        at com.google.firebase.ml.common.modeldownload.FirebaseModelManager.zza(Unknown Source:73)
        at com.google.firebase.ml.common.modeldownload.zzc.then(Unknown Source:2)
        at com.google.android.gms.tasks.zzp.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:898)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at com.google.android.gms.internal.firebase_ml.zzf.dispatchMessage(Unknown Source:6)
        at android.os.Looper.loop(Looper.java:198)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.firebase.ml.common.FirebaseMLException: Failed to connect to Firebase ML console server with HTTP status code: 404 and error message: {
      "error": {
        "code": 404,
        "message": "Requested entity was not found.",
        "status": "NOT_FOUND"
      }
    }`

Thanks for your help.

**Comment by khanhlvg** [comment]
Hi,

The error means that your remote model is not properly registered in your Firebase project. Can you check if you're using the correct google-services.json from your Firebase project, and the name of the remote model that you registered in Firebase match with the one in the Android app?
